### ISSUE TITLE
Why are you doing this

### ISSUE THREAD

**Issue by DarrenOfficial** [Akshit1025/discordjs-music-bot#3]
read the title

![bug](https://cdn.darrennathanael.com/assets/discord/B736BC0A-C925-41A9-AAE7-1C75E7153F78.jpeg)
![gif](https://cdn.darrennathanael.com/assets/discord/B38AAB36-4A75-4A5F-B929-8866D63F06CD.jpeg)

**Comment by Akshit1025** [comment]
cause I want the users to be redirected to my GitHub not Sudan's

**Comment by JotaroKujo0525** [comment]
Yikes

**Comment by JotaroKujo0525** [comment]
Like you can just remove the credits. But don't replace the credits to yourself

**Comment by DarrenOfficial** [comment]
and def don’t make a repo to “cause I want the users to be redirected to my GitHub not Sudan's”

**Comment by DarrenOfficial** [comment]
like forking is a thing

**Comment by JotaroKujo0525** [comment]
> like forking is a thing

Ye, just fork it

**Comment by Akshit1025** [comment]
I am closing this issue and as well as making the repo archived and it will not receive any new updates
